from enum import Enum


class TelemeryType(str, Enum):

    # Configuration Phase
    CONFIG_LOAD_START = "CONFIG_LOAD_START"
    CONFIG_LOAD_COMPLETE = "CONFIG_LOAD_COMPLETE"
    CONFIG_LOAD_ERROR = "CONFIG_LOAD_ERROR"

    # Compilation Phase
    COMPILATION_START = "COMPILATION_START"
    COMPILATION_COMPLETE = "COMPILATION_COMPLETE"
    COMPILATION_ERROR = "COMPILATION_ERROR"

    # Container Build Phase
    CONTAINER_BUILD_START = "CONTAINER_BUILD_START"
    COMPONENT_INSTANTIATED = "COMPONENT_INSTANTIATED"
    CONTAINER_BUILD_COMPLETE = "CONTAINER_BUILD_COMPLETE"

    # Runtime Phase
    RUNTIME_PHASE_START = "RUNTIME_PHASE_START"
    RUNTIME_PHASE_COMPLETE = "RUNTIME_PHASE_COMPLETE"
    RUNTIME_PHASE_ERROR = "RUNTIME_PHASE_ERROR"
    AGENT_EVENT_EMITTED = "AGENT_EVENT_EMITTED"
    RUNTIME_UNKNOWN_THREAD_FAILURE = "RUNTIME_UNKNOWN_THREAD_FAILURE"

    # Timeout check events
    TIMEOUT_CLOSE_SUCCESS = "TIMEOUT_CLOSE_SUCCESS"
    TIMEOUT_CLOSE_CAS_FAILURE = "TIMEOUT_CLOSE_CAS_FAILURE"
    ACTIVE_THREAD_REJECTED = "ACTIVE_THREAD_REJECTED"
    # resume events
    RESUME_AUTH_FAILURE = "RESUME_AUTH_FAILURE"
    RESUME_INVALID_TOKEN_FAILURE = "RESUME_INVALID_TOKEN_FAILURE"

    # Agent Phase
    AGENT_RUN_START = "AGENT_RUN_START"
    AGENT_RUN_COMPLETE = "AGENT_RUN_COMPLETE"
    AGENT_RUN_ERROR = "AGENT_RUN_ERROR"


class TelemetryComponent(str, Enum):
    CONFIG_LOADER = "CONFIG_LOADER"
    COMPONENT_COMPILER = "COMPONENT_COMPILER"
    CONTAINER = "FLOTILLA_CONTAINER"
    RUNTIME = "FLOTILLA_RUNTIME"
    APPLICATION = "FLOTILLA_APPLICATION"
    AGENT = "FLOTILLA_AGENT"
