from enum import Enum


class TelemeryType(str, Enum):
    # Configuration Phase
    CONFIG_LOAD_START = "CONFIG_LOAD_START"
    CONFIG_LOAD_COMPLETE = "CONFIG_LOAD_COMPLETE"
    CONFIG_VALIDATION_ERROR = "CONFIG_VALIDATION_ERROR"
    # Compilation Phase
    COMPILATION_START = "COMPILATION_START"
    COMPILATION_COMPLETE = "COMPILATION_COMPLETE"
    REF_RESOLUTION = "REF_RESOLUTION"
    COMPILATION_ERROR = "COMPILATION_ERROR"

    # Container Build Phase
    CONTAINER_BUILD_START = "CONTAINER_BUILD_START"
    COMPONENT_INSTANTIATED = "COMPONENT_INSTANTIATED"
    CONTAINER_BUILD_COMPLETE = "CONTAINER_BUILD_COMPLETE"

    # Runtime Phase
    RUNTIME_REQUEST_RECEIVED = "RUNTIME_REQUEST_RECEIVED"
    RUNTIME_PHASE_INITIATED = "RUNTIME_PHASE_INITIATED"
    AGENT_EVENT_EMITTED = "AGENT_EVENT_EMITTED"
    RUNTIME_TERMINAL = "RUNTIME_TERMINAL"

    # Agent Phase
    AGENT_RUN_START = "AGENT_RUN_START"
    AGENT_RUN_COMPLETE = "AGENT_RUN_COMPLETE"
    AGENT_RUN_ERROR = "AGENT_RUN_ERROR"


class TelemetryComponent(str, Enum):
    CONFIG_LOADER = "CONFIG_LOADER"
    COMPONENT_COMPILER = "COMPONENT_COMPILER"
    CONTAINER = "FLOTILLA_CONTAINER"
    RUNTIME = "FLOTILLA_RUNTIME"
    APPLICATION = "FLOTILLA_APPLICATION"
    FLOTILLA_AGENT = "FLOTILLA_AGENT"
