LLM:
  API_KEY: null
  MODEL: "gpt-4o-mini"
  TEMPERATURE: 0
  TYPE: "openai"

LOG:
  LEVEL: "INFO"

TOOL_REGISTRY:
  PACKAGES:
    - "tools"
  RECURISVE: true
  ENABLE_DISCOVERY: true

AGENT_REGISTRY:
  PACKAGES:
    - "agents"
  RECURSIVE: true
  ENABLE_DISCOVERY: true